### ISSUE TITLE
Wrong override of U+07FD NKO DANTAYALAN

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#10]
U+07FD NKO DANTAYALAN is overridden to USE class FM. It should instead be in VMAbv, the same as the other N’Ko marks.

U+07FD has ccc=220. U+07EB NKO COMBINING SHORT HIGH TONE (for example) has USE class VMAbv and ccc=230. Therefore, in NFC text, U+07FD precedes U+07EB, but with the current override USE requires the opposite order.

**Comment by xadxura** [comment]
Fixed, thank you!

**Comment by xadxura** [comment]
Added an IPC override to set 07FD as 'top' so that ccc can control the mark order.
