### ISSUE TITLE
Reserved code points shouldn’t be included in the range

### ISSUE THREAD

**Issue by lianghai** [microsoft/font-tools#12]
There’re 15 code points still “reserved” but are included in the range 1BC00..1BC99 and are prematurely assigned an override value:

https://github.com/microsoft/font-tools/blob/d2eb814c4128d00d5e807504f4951528e5973c67/USE/IndicSyllabicCategory-Additional.txt#L99

**Comment by xadxura** [comment]
Fixed, thank you!
