### ISSUE TITLE
USE override for Tulu-Tigalari

### ISSUE THREAD

**Issue by NorbertLindenberg** [microsoft/font-tools#17]
The UTC has approved proposal [L2/22-031](https://www.unicode.org/L2/L2022/22031-tulu-tigalari-prop.pdf) to encode the Tulu-Tigalari script in a future version of the Unicode Standard. Pages 22-23 of the proposal discuss the need to override the Indic syllabic category of the Tulu-Tigalari Virama with the value Bindu.

Please implement that override when the future version arrives.

**Comment by virtualvinodh** [comment]
This also includes an override for Tulu-Tigalari Virama as explained on page 24.

> We suggest a USE override for the Looped Virama by assigning it the value of 'Consonant Modifier'.

V

**Comment by xadxura** [comment]
@virtualvinodh, @NorbertLindenberg is the following what you expect?:

113CE         ; Bindu  # Mn       TULU-TIGALARI SIGN VIRAMA
113CF         ; Nukta  # Mc       TULU-TIGALARI SIGN LOOPED VIRAMA

**Comment by NorbertLindenberg** [comment]
Looks like what Dr Vinodh prescribed.

**Comment by NorbertLindenberg** [comment]
Turns out that the override for 113CF doesn't work: It creates a CONS_MOD with InPC=Right, which the USE doesn't support. Tulu-Tigalari already has a CONS_MOD with InPC=Bottom, 113D2, so just overriding 113CF with that value doesn't work either.

**Comment by xadxura** [comment]
Reopening to apply solution proposed by @dscorbett.
