### ISSUE TITLE
Likely incorrect override for syllabic category of Balinese combining marks 

### ISSUE THREAD

**Issue by NorbertLindenberg** [microsoft/font-tools#18]
The file IndicSyllabicCategory-Additional.txt has the following entry:

>1B6B..1B73    ; Nukta            # Mn   [9] BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG

This override is very likely incorrect. According to the Unicode Standard section 17.3, these characters are part of the musical symbols and intended to be used with base characters or this set. There is no indication that they’re meant to be used as part of regular Balinese orthographic syllables. The USE specification has a special class SYM_MOD just for these characters and a special symbol cluster that allows characters from this class to attach to SYM characters, including the other Balinese musical symbols. The override prevents these attachments and enables incorrect ones.

**Comment by xadxura** [comment]
Thank you, @NorbertLindenberg, good catch.
Fixed pushed to Unicode 15 branch. I'll merge that branch in September.
