### ISSUE TITLE
USE overrides for Batak vowel killers

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#20]
For the reason given in harfbuzz/harfbuzz#627, the sequence <vowel, vowel killer> should be considered an error in Batak and should get a dotted circle. The best solution is to override the two vowel killers to Indic_Syllabic_Category = Nukta and Indic_Positional_Category = Bottom.

**Comment by xadxura** [comment]
@dscorbett, good issue, and good suggestion. Thank you!
Fixed in Unicode15 branch, which I will merge in September.
