### ISSUE TITLE
USE overrides for Kayah Li vowel signs

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#21]
The Kayah Li vowel signs U+A926..U+A92A do not match any USE subclass and therefore form independent clusters, which was surely not intended. Their Indic_Positional_Category should be overridden to Top, which will make them match VOWEL_ABOVE. (I have also reported this to Unicode, but for now the overrides are necessary.)

**Comment by xadxura** [comment]
These are now defined in Unicode 15 data, so no need to apply them in the overrides files at this point.
