### ISSUE TITLE
USE overrides for cantillation marks U+1CF8 and U+1CF9

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#24]
The cantillation marks U+1CF8 and U+1CF9 do not match any USE subclass and therefore form independent clusters, which was surely not what was intended. Their Indic_Positional_Category should be overridden to Top, which will make them match VOWEL_MOD_ABOVE.

**Comment by xadxura** [comment]
Thank you! I've added overrides for these code points to ISC= Cantillation_Mark; and IPC = Top.
