### ISSUE TITLE
USE overrides for Chakma below-base vowel signs

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#25]
USE currently overrides all Chakma above-base vowel signs to have Indic_Positional_Category=Bottom. This means that a cluster with an above-base vowel sign and a below-base vowel sign can be written in either order, with no dotted circle inserted. For example, <U+11132, U+11127> and <U+11127, U+11132> look identical because USE considers both valid. To encourage people to use one order consistently, only one of those should be considered valid. Because the canonical decomposition of U+1112F is <U+11132, U+11127>, that order must be valid. Therefore, <U+11127, U+11132> should not be considered valid: a dotted circle should be inserted. To that end, all Chakma below-base vowel signs (U+1112A, U+1112B, U+11131, and U+11132) should be overridden to have Indic_Positional_Category=Top.

**Comment by xadxura** [comment]
Good call. Thanks for the suggested solution! Fix pushed to Unicode15 branch.
