### ISSUE TITLE
Unnecessary override of U+1172B AHOM SIGN KILLER

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#3]
https://github.com/microsoft/font-tools/issues/2#issuecomment-668393687 says:

>Ahom sign killer needs to be able to render with vowels, so override ISC to Bindu (i.e., vowel modifier).

Unicode assigns Indic_Syllabic_Category=Pure_Killer to U+1172B AHOM SIGN KILLER. USE maps Pure_Killer to VOWEL. Therefore, it can already render with vowels and this override is unnecessary.

**Comment by xadxura** [comment]
I moved this to the Bindu (i.e. vowel modifier) class because uses need to be able to enter this after the post-base vowel sign AA, U+11721. The current ISC assignment would make this a vowel, and therefore it's IPC assignment 'Top' would require it to come before the post-base vowel.
