### ISSUE TITLE
Duplicate overrides in IndicSyllabicCategory-Additional.txt

### ISSUE THREAD

**Issue by NorbertLindenberg** [microsoft/font-tools#38]
The file IndicSyllabicCategory-Additional.txt contains a few overrides in duplicate:

– The entire section for Vowel_Independent with overrides for three Tai Viet characters is duplicated.

– The line for 1820..1878 duplicates the override for the immediately following 1843, although with an incorrect general category in the comment.

**Comment by xadxura** [comment]
Fixed, thank you Norbert!

**Comment by behdad** [comment]
@dscorbett Anything we need to update in HarfBuzz?

**Comment by dscorbett** [comment]
No: this was about duplicated data, so regardless of how HarfBuzz read the file it was already getting the correct values.
