### ISSUE TITLE
MAKE IT WORK

### ISSUE THREAD

**Issue by solnyszczko** [microsoft/font-tools#39]
PLEASE I WANT A GOOD EGYPTIAN HIEROGLYPH FONT THAT JUST WORKS AAAAAA

**Comment by xadxura** [comment]
My project for December '23. Font is almost ready!

**Comment by behdad** [comment]
Congrats!

**Comment by solnyszczko** [comment]
woooooooooo

**Comment by xadxura** [comment]
The font is now available:
https://github.com/microsoft/font-tools/tree/main/EgyptianOpenType/font

Note that support for shaping Egyptian Hieroglyphic format controls varies across different applications. HarfBuzz is working well at this time. :)

**Comment by solnyszczko** [comment]
𓂸 𓂸 𓂸 𓃴 𓂺 𓃴 𓂺 𓃴 𓂺
