### ISSUE TITLE
Zanabazar Square needs override to permit multiple medial vowels

### ISSUE THREAD

**Issue by xadxura** [microsoft/font-tools#48]
Per Unicode SAH: https://github.com/unicode-org/sah/issues/359 
Zanabazar Square needs ISC overrides for the Zanabazar Cluster Finals to permit multiple occurences in a cluster.

**Comment by NorbertLindenberg** [comment]
If successful, this would fix [USE bug 981](https://github.com/MicrosoftDocs/typography-issues/issues/981).

**Comment by xadxura** [comment]
Candidate values:
# Zanabazar Square
11A3A        ; Consonant_With_Stacker # Lo     ZANABAZAR SQUARE CLUSTER-INITIAL LETTER RA
11A3B..11A3E ; Nukta                  # Mn [4] ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA..ZANABAZAR SQUARE CLUSTER-FINAL LETTER VA

**Comment by xadxura** [comment]
See also: https://github.com/notofonts/zanabazar-square/issues/8

**Comment by dscorbett** [comment]
Instead of Nukta for the cluster-final letters, I suggest Consonant_Subjoined. It comes to the same thing in the context of this script, but it is a more accurate description of these characters.
