### ISSUE TITLE
Manichaean abbreviation marks need positional overrides

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#5]
U+10AE5 MANICHAEAN ABBREVIATION MARK ABOVE and U+10AE6 MANICHAEAN ABBREVIATION MARK BELOW are non-[starters](https://www.unicode.org/glossary/#starter). NFC puts the below-base one first whereas USE specifies that CMAbv precedes CMBlw. Like Tibetan vowel signs, their positional categories need overriding to allow U+10AE6 to precede U+10AE5.

**Comment by xadxura** [comment]
Moved both to Bottom so the order can be controlled by ccc.
