### ISSUE TITLE
How to query Unicode version supported by your running OS ?

### ISSUE THREAD

**Issue by ohault** [microsoft/font-tools#50]
ChatGTP GTP-4o provides the following table but how to query the supported Unicode version of your running Windows version ?

<html>
<body>
<div data-message-author-role="assistant" data-message-id="5b9f4690-3dcb-428b-a747-00040f08edc1" dir="auto" class="min-h-[20px] text-message flex flex-col items-start whitespace-pre-wrap break-words [.text-message+&amp;]:mt-5 juice:w-full juice:items-end overflow-x-auto gap-2" style="border: 0px solid rgb(227, 227, 227); box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(69,89,164,.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-shadow-colored: 0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; display: flex; min-height: 20px; flex-direction: column; align-items: flex-end; gap: 0.5rem; overflow-x: auto; white-space: pre-wrap; overflow-wrap: break-word; width: 712px; color: rgb(13, 13, 13); font-family: Söhne, ui-sans-serif, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, &quot;Helvetica Neue&quot;, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="flex w-full flex-col gap-1 juice:empty:hidden juice:first:pt-[3px]" style="border: 0px solid rgb(227, 227, 227); box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(69,89,164,.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-shadow-colored: 0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; display: flex; width: 712px; flex-direction: column; gap: 0.25rem; padding-top: 3px;"><div class="markdown prose w-full break-words dark:prose-invert light" style="border: 0px solid rgb(227, 227, 227); box-sizing: border-box; --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(69,89,164,.5); --tw-ring-offset-shadow: 0 0 transparent; --tw-ring-shadow: 0 0 transparent; --tw-shadow: 0 0 transparent; --tw-shadow-colored: 0 0 transparent; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; color: var(--tw-prose-body); max-width: none; --tw-prose-body: var(--text-primary); --tw-prose-headings: var(--text-primary); --tw-prose-lead: var(--text-primary); --tw-prose-links: var(--text-primary); --tw-prose-bold: var(--text-primary); --tw-prose-counters: var(--text-primary); --tw-prose-bullets: var(--text-primary); --tw-prose-hr: var(--border-xheavy); --tw-prose-quotes: var(--text-primary); --tw-prose-quote-borders: #e5e7eb; --tw-prose-captions: var(--text-secondary); --tw-prose-code: var(--text-primary); --tw-prose-pre-code: #e5e7eb; --tw-prose-pre-bg: #1f2937; --tw-prose-th-borders: #d1d5db; --tw-prose-td-borders: #e5e7eb; --tw-prose-invert-body: var(--text-primary); --tw-prose-invert-headings: var(--text-primary); --tw-prose-invert-lead: var(--text-primary); --tw-prose-invert-links: var(--text-primary); --tw-prose-invert-bold: var(--text-primary); --tw-prose-invert-counters: var(--text-primary); --tw-prose-invert-bullets: var(--text-primary); --tw-prose-invert-hr: var(--border-xheavy); --tw-prose-invert-quotes: var(--text-primary); --tw-prose-invert-quote-borders: #374151; --tw-prose-invert-captions: var(--text-secondary); --tw-prose-invert-code: var(--text-primary); --tw-prose-invert-pre-code: #d1d5db; --tw-prose-invert-pre-bg: rgba(0,0,0,.5); --tw-prose-invert-th-borders: #4b5563; --tw-prose-invert-td-borders: #374151; font-size: 1rem; line-height: 1.75; width: 712px; overflow-wrap: break-word;">
Windows Version/Build Number | Unicode Version
-- | --
Windows 3.1 (Build 103) | None
Windows 95 (Build 950) | None
Windows 98 (Build 1998) | None
Windows ME (Build 3000) | None
Windows NT 3.1 (Build 511) | Unicode 1.1
Windows NT 3.5 (Build 807) | Unicode 1.1
Windows NT 3.51 (Build 1057) | Unicode 1.1
Windows NT 4.0 (Build 1381) | Unicode 2.0
Windows 2000 (Build 2195) | Unicode 2.1
Windows XP (Build 2600) | Unicode 3.0
Windows Server 2003 (Build 3790) | Unicode 3.1
Windows Vista (Build 6000) | Unicode 4.1
Windows 7 (Build 7600) | Unicode 5.1
Windows 8 (Build 9200) | Unicode 6.1
Windows 8.1 (Build 9600) | Unicode 6.3
Windows 10 (1507, Build 10240) | Unicode 6.3
Windows 10 (1511, Build 10586) | Unicode 7.0
Windows 10 (1607, Build 14393) | Unicode 8.0
Windows 10 (1703, Build 15063) | Unicode 9.0

</div></div></div>
</body>
</html>

**Comment by xadxura** [comment]
I'm not aware of that being programmatically available. Most components in current Windows builds have been updated for Unicode 15.1.

**Comment by ohault** [comment]
For linguistic apps, that's a big issue. An API should exist to know the Unicode version of the running Windows and to also query all the particularities. Does it possible to add this to your roadmap?
