### ISSUE TITLE
USE overrides for Unicode 16

### ISSUE THREAD

**Issue by xadxura** [microsoft/font-tools#51]
Update IndicPositionalCategory-Additional.txt and IndicSyllabicCategory-Additional.txt for Unicode 16.

**Comment by behdad** [comment]
cc @dscorbett

**Comment by NorbertLindenberg** [comment]
The PR has changes for Ol Onal, Garay, Khitan Small Script whose motivation isn't described in any of the issues referenced by the commit. Can you add some info?
