### ISSUE TITLE
Override for Balinese Musical Symbol Combining Endep

### ISSUE THREAD

**Issue by xadxura** [microsoft/font-tools#53]
1B6C          ; Top   # Mn       BALINESE MUSICAL SYMBOL COMBINING ENDEP

**Comment by NorbertLindenberg** [comment]
Why?

**Comment by xadxura** [comment]
This is standard procedure with signs that have ccc values in the same class but differ formally by position. We have to allow normalization to control the order so we override we override them into the same position.
