### ISSUE TITLE
U+1BC9D DUPLOYAN THICK LETTER SELECTOR matches no USE class

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#6]
U+1BC9D DUPLOYAN THICK LETTER SELECTOR gets Indic_Syllabic_Category=Nukta and Indic_Positional_Category=Not_Applicable. USE does not specify what to do about positionless nuktas: there are only CMAbv and CMBlw. I recommend Indic_Positional_Category=Overstruck for U+1BC9D so it can appear before or after U+1BC9E DUPLOYAN DOUBLE MARK. (I have found no attestation of a shaded double mark, but it is logically possible, and there is no need to disallow it.)

**Comment by xadxura** [comment]
Added, thank you!
