### ISSUE TITLE
Wrong overrides of U+11003..U+11004 BRAHMI SIGN JIHVAMULIYA/UPADHMANIYA

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#7]
Unicode assigns Indic_Syllabic_Category=Consonant_With_Stacker to U+11003 BRAHMI SIGN JIHVAMULIYA and U+11004 BRAHMI SIGN UPADHMANIYA. USE overrides them to Indic_Syllabic_Category=Consonant. Why? “They enter into ligatures with the following homorganic voiceless stop consonant, without the use of a <i>virama</i>”, [according to <i>The Unicode Standard</I>](https://www.unicode.org/versions/Unicode13.0.0/ch14.pdf#page=5), which makes them consonants with stackers.

**Comment by xadxura** [comment]
This was originally intended to be MS-specific, but is no longer needed. Removing.
