### ISSUE TITLE
Visually ambiguous order of U+10A0C KHAROSHTHI VOWEL LENGTH MARK

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#8]
Unicode assigns Indic_Syllabic_Category=Vowel_Dependent and Indic_Positional_Category=Bottom to U+10A0C KHAROSHTHI VOWEL LENGTH MARK, which would put in USE class VBlw. USE overrides it to Indic_Syllabic_Category=Bindu and Indic_Positional_Category=Top, putting it in VMAbv. Why? Kharoshthi already has another character in VMAbv: U+10A0F KHAROSHTHI SIGN VISARGA. If U+10A0C and U+10A0F are in the same class, they may occur in either order; since they don’t really have the same position, this introduces a visual ambiguity.

If the goal is that the vowel length mark follow vowels and precede U+10A0D KHAROSHTHI SIGN DOUBLE RING BELOW, one solution is Indic_Syllabic_Category=Vowel_Dependent and Indic_Positional_Category=Right.

**Comment by xadxura** [comment]
Nice suggestion!
