### ISSUE TITLE
U+16FE4 KHITAN SMALL SCRIPT FILLER should not have InSC=Virama

### ISSUE THREAD

**Issue by dscorbett** [microsoft/font-tools#9]
U+16FE4 KHITAN SMALL SCRIPT FILLER is overridden to Indic_Syllabic_Category=Virama, but that is wrong. Also, it is not useful.

By default, a sequence of Khitan small script letters is rendered as a cluster (similar to a Hangul syllable block) with two letters per row. U+16FE4 forces the preceding letter to be on a row by itself and pushes the following letter onto the next row. U+16FE4 separates letters, whereas a virama joins them, so the override is wrong.

Each KSS letter has USE class BASE. One KSS cluster therefore corresponds to multiple USE clusters (one USE cluster per letter). That makes USE clustering not particularly useful for KSS. Having U+16FE4 put the two surrounding letters in the same USE cluster will still not put the whole KSS cluster into a single USE cluster, so the override is not useful.

**Comment by xadxura** [comment]
Fixed, thank you!
